version: '3.8'

services:

  angular:
    image: educacao-front
    restart: always
    ports:
      - "8089:80"

  eureka-server:
    image: ms-server
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      - ${EUREKA_SERVER_URL}=${EUREKA_SERVER_URL}

  eureka-gateway:
    image: ms-gateway
    restart: always
    ports:
      - "8082:8082"
    env_file:
      - .env
    environment:
      - ${EUREKA_SERVER_URL}=${EUREKA_SERVER_URL}
    depends_on:
      - eureka-server
      - angular
    
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  core:
    image: ms-core/ms-core:core-main
    container_name: core
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    env_file:
      - .env
    environment:
      - ${EUREKA_SERVER_URL}=${EUREKA_SERVER_URL}
      - ${SPRING_RABBITMQ_ADDRESSES}=${SPRING_RABBITMQ_ADDRESSES}
      - ${DB_HOST}=${DB_HOST}
      - ${DB_PORT_DEFAULT}=${DB_PORT_DEFAULT}
      - ${DB_DEFAULT}=${DB_DEFAULT}

    depends_on:
      - db
      - eureka-server
      - eureka-gateway
      - rabbitmq
      - angular

#networks:
 # eureka-network:
