version: '3.8'

services:
  eureka-server:
    image: ms-server/ms-server:server
    build:
      context: ./../ms-server-educacao
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - eureka-network

  eureka-gateway:
    image: ms-gateway/ms-gateway:gateway
    build:
      context: ./../ms-gateway-educacao
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - ${EUREKA_SERVER_URL}=${EUREKA_SERVER_URL}
    networks:
      - eureka-network
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - eureka-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - eureka-network

  app:
    image: ms-core/ms-core:core-main
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    env_file:
      - .env
    environment:
      - ${EUREKA_SERVER_URL}=${EUREKA_SERVER_URL}
      - ${SPRING_RABBITMQ_ADDRESSES}=${SPRING_RABBITMQ_ADDRESSES}
      - ${DB_HOST}=${DB_HOST}
      - ${DB_PORT_DEFAULT}=${DB_PORT_DEFAULT}
      - ${DB_DEFAULT}=${DB_DEFAULT}

    depends_on:
      - db
      - eureka-server
      - eureka-gateway
      - rabbitmq
    networks:
      - eureka-network

networks:
  eureka-network:
    driver: bridge
