package br.com.coreeduc.aplication.services;

import br.com.coreeduc.aplication.entities.AbastecimentoAguaEntity;
import br.com.coreeduc.aplication.entities.AcessoInternetEntity;
import br.com.coreeduc.aplication.entities.DependenciasFisicasEntity;
import br.com.coreeduc.aplication.entities.DestinacaoLixoEntity;
import br.com.coreeduc.aplication.entities.EquipamentosExistentesUnidadeEntity;
import br.com.coreeduc.aplication.entities.EquipamentosUsadosAlunosAcessoInternetEntity;
import br.com.coreeduc.aplication.entities.EscolasComQualCompartilhaEntity;
import br.com.coreeduc.aplication.entities.EsgotamentoSanitarioEntity;
import br.com.coreeduc.aplication.entities.FonteEnergiaEletricaEntity;
import br.com.coreeduc.aplication.entities.LocalFuncionamentoEscolaEntity;
import br.com.coreeduc.aplication.entities.QuantidadeComputadoresEmUsoAlunosEntity;
import br.com.coreeduc.aplication.entities.QuantidadeEquipamentosProcessoAprendizagemEntity;
import br.com.coreeduc.aplication.entities.RecursoPessoasDeficientesEntity;
import br.com.coreeduc.aplication.entities.TratamentoLixoEntity;
import br.com.coreeduc.aplication.entities.UnidadeEnsinoEntity;
import br.com.coreeduc.aplication.records.DisabledPeopleResourceEducacensoRecord;
import br.com.coreeduc.aplication.records.ElectricEnergySourceEducacensoRecord;
import br.com.coreeduc.aplication.records.ExistingUnitEquipmentEducacensoRecord;
import br.com.coreeduc.aplication.records.InternetAccessEducacensoRecord;
import br.com.coreeduc.aplication.records.NumberComputersInUseByStudentsEducacensoRecord;
import br.com.coreeduc.aplication.records.PhysicalDependenciesEducacensoRecord;
import br.com.coreeduc.aplication.records.QuantityEquipmentLearningProcessEducacensoRecord;
import br.com.coreeduc.aplication.records.SanitarySewageEducacensoRecord;
import br.com.coreeduc.aplication.records.SchoolLocationEducacensoRecord;
import br.com.coreeduc.aplication.records.SchoolParticipationEducacensoRecord;
import br.com.coreeduc.aplication.records.UsedEquipmentStudentsInternetAccessEducacensoRecord;
import br.com.coreeduc.aplication.records.WasteDisposalEducacensoRecord;
import br.com.coreeduc.aplication.records.WasteTreatmentEducacensoRecord;
import br.com.coreeduc.aplication.records.WaterSupplyEducacensoRecord;

public interface EducacensoUnitService extends EducacensoService{
    UnidadeEnsinoEntity convetSerializedMessageInUnitEntity(String serializedMessage);
    LocalFuncionamentoEscolaEntity convertSchoolLocationRecordInEntity(SchoolLocationEducacensoRecord schoolLocationEducacensoRecord);
    EscolasComQualCompartilhaEntity convertScoolParticipationRecordInEntity(SchoolParticipationEducacensoRecord schoolParticipationEducacensoRecord);
    AbastecimentoAguaEntity convertWaterSupplyRecordInEntity(WaterSupplyEducacensoRecord waterSupplyEducacensoRecord);
    FonteEnergiaEletricaEntity convertEletricEnergySourceRecordInEntity(ElectricEnergySourceEducacensoRecord electricEnergySourceEducacensoRecord);
    EsgotamentoSanitarioEntity convertSanitarySewageRecordInEntity(SanitarySewageEducacensoRecord sanitarySewageEducacensoRecord);
    DestinacaoLixoEntity convertWasteDisposalRecordInEntity(WasteDisposalEducacensoRecord wasteDisposalEducacensoRecord);
    TratamentoLixoEntity convertWasteTreatmentRecordInentity(WasteTreatmentEducacensoRecord wasteTreatmentEducacensoRecord);
    DependenciasFisicasEntity convertPhysicalDependenciesRecordInEntity(PhysicalDependenciesEducacensoRecord physicalDependenciesEducacensoRecord);
    RecursoPessoasDeficientesEntity convertDisabledPeopleResourceRecordInEntity(DisabledPeopleResourceEducacensoRecord disabledPeopleResourceEducacensoRecord);
    EquipamentosExistentesUnidadeEntity convertExistingUnitEquipmentRecordInEntity(ExistingUnitEquipmentEducacensoRecord existingUnitEquipmentEducacensoRecord);
    QuantidadeEquipamentosProcessoAprendizagemEntity quantityEquimentLearningProcessRecordInEntity(QuantityEquipmentLearningProcessEducacensoRecord quantityEquipmentLearningProcessEducacensoRecord);
    QuantidadeComputadoresEmUsoAlunosEntity convertComputersInUseByStudentsRecordInEntity(NumberComputersInUseByStudentsEducacensoRecord numberComputersInUseByStudentsEducacensoRecord);
    AcessoInternetEntity convertAccessEducacensoRecordInEntity(InternetAccessEducacensoRecord internetAccessEducacensoRecord);
    EquipamentosUsadosAlunosAcessoInternetEntity convertEquipmentStudentsInternetAccessRecordInEntity(UsedEquipmentStudentsInternetAccessEducacensoRecord numberComputersInUseByStudentsEducacensoRecord);
}
