package br.com.coreeduc.aplication.domains.contraints;

/**
 * @author Alex Buttielie Alves Guimarães
 *
 */
public enum Paises {

        AFEGANISTAO (4,"AFG", "AFEGANISTÃO"),
        ALBANIA(8,"ALB", "ALBÂNIA" ),
        ARGELIA(12,"DZA", "ARGÉLIA"),
        SAMOA_AMERICANA(16,"ASM", "SAMOA AMERICANA"),
        ANDORRA(20,"AND", "ANDORRA"),
        ANGOLA (24,"AGO", "ANGOLA" ),
        ANTIGUA_E_BARBUDA(28,"ATG", "ANTÍGUA E BARBUDA"),
        AZERBAIJAO(31,"AZE", "AZERBAIJÃO"),
        ARGENTINA (32,"ARG", "ARGENTINA" ),
        AUSTRALIA (36,"AUS", "AUSTRÁLIA" ),
        AUSTRIA(40,"AUT", "ÁUSTRIA"),
        BAHAMAS(44,"BHS", "BAHAMAS"),
        BAHREIN(48,"BHR", "BAHREIN"),
        BANGLADESH(50,"BGD", "BANGLADESH"),
        ARMENIA(51,"ARM", "ARMÊNIA"),
        BARBADOS(52,"BRB", "BARBADOS"),
        BELGICA(56,"BEL", "BÉLGICA"),
        BERMUDAS(60,"BMU", "BERMUDAS"),
        BUTAO(64,"BTN", "BUTÃO"),
        BOLIVIA_ESTADO_PLURINACIONAL_DA (68,"BOL", "BOLÍVIA (ESTADO PLURINACIONAL DA)"),
        BOSNIA_E_HERZEGOVINA(70,"BIH", "BÓSNIA E HERZEGOVINA"),
        BOTSUANA(72,"BWA", "BOTSUANA"),
        BRASIL (76,"BRA", "BRASIL" ),
        BELIZE (84,"BLZ", "BELIZE" ),
        ILHAS_SALOMAO(90,"SLB", "ILHAS SALOMÃO"),
        ILHAS_VIRGENS_BRITANICAS (92,"VGB", "ILHAS VIRGENS BRITÂNICAS" ),
        BRUNEI (96,"BRN", "BRUNEI" ),
        BULGARIA(100, "BGR", "BULGÁRIA"),
        MYANMAR(104, "MMR", "MYANMAR"),
        BURUNDI(108, "BDI", "BURUNDI"),
        BIELORRUSSIA(112, "BLR", "BIELORRÚSSIA"),
        CAMBOJA(116, "KHM", "CAMBOJA"),
        CAMAROES(120, "CMR", "CAMARÕES"),
        CANADA (124, "CAN", "CANADÁ" ),
        CABO_VERDE(132, "CPV", "CABO VERDE"),
        ILHAS_CAIMAN(136, "CYM", "ILHAS CAIMAN"),
        REPUBLICA_CENTRO_AFRICANA(140, "CAF", "REPÚBLICA CENTRO AFRICANA"),
        SRI_LANKA (144, "LKA", "SRI LANKA" ),
        CHADE(148, "TCD", "CHADE"),
        CHILE(152, "CHL", "CHILE"),
        CHINA(156, "CHN", "CHINA"),
        COLOMBIA(170, "COL", "COLÔMBIA"),
        COMORES(174, "COM", "COMORES"),
        MAYOTTE(175, "MYT", "MAYOTTE"),
        CONGO(178, "COG", "CONGO"),
        REPUBLICA_DEMOCRATICA_DO_CONGO(180, "COD", "REPÚBLICA DEMOCRÁTICA DO CONGO"),
        ILHAS_COOK(184, "COK", "ILHAS COOK"),
        COSTA_RICA(188, "CRI", "COSTA RICA"),
        CROACIA(191, "HRV", "CROÁCIA"),
        CUBA(192, "CUB", "CUBA"),
        CHIPRE (196, "CYP", "CHIPRE" ),
        REPUBLICA_TCHECA (203, "CZE", "REPÚBLICA TCHECA" ),
        BENIN(204, "BEN", "BENIN"),
        DINAMARCA (208, "DNK", "DINAMARCA" ),
        DOMINICA(212, "DMA", "DOMINICA"),
        REPUBLICA_DOMINICANA(214, "DOM", "REPÚBLICA DOMINICANA"),
        EQUADOR(218, "ECU", "EQUADOR"),
        EL_SALVADOR (222, "SLV", "EL SALVADOR" ),
        GUINE_EQUATORIAL (226, "GNQ", "GUINÉ EQUATORIAL" ),
        ETIOPIA(231, "ETH", "ETIÓPIA"),
        ERITREIA(232, "ERI", "ERITRÉIA"),
        ESTONIA(233, "EST", "ESTÔNIA"),
        ILHAS_FEROE (234, "FRO", "ILHAS FEROE" ),
        ILHAS_MALVINAS (238, "FLK", "ILHAS MALVINAS" ),
        FIJI(242, "FJI", "FIJI"),
        FINLANDIA (246, "FIN", "FINLÂNDIA" ),
        ALAND_ILHAS (248, "ALA", "ÅLAND ILHAS"),
        FRANCA (250, "FRA", "FRANÇA" ),
        GUIANA_FRANCESA(254, "GUF", "GUIANA FRANCESA"),
        POLINESIA_FRANCESA(258, "PYF", "POLINÉSIA FRANCESA"),
        DJIBUTI(262, "DJI", "DJIBUTI"),
        GABAO(266, "GAB", "GABÃO"),
        GEORGIA(268, "GEO", "GEÓRGIA"),
        GAMBIA (270, "GMB", "GÂMBIA" ),
        PALESTINA (275, "PSE", "PALESTINA" ),
        ALEMANHA(276, "DEU", "ALEMANHA"),
        GANA(288, "GHA", "GANA"),
        GIBRALTAR (292, "GIB", "GIBRALTAR" ),
        QUIRIBATI (296, "KIR", "QUIRIBATI" ),
        GRECIA (300, "GRC", "GRÉCIA" ),
        GROENLANDIA (304, "GRL", "GROENLÂNDIA" ),
        GRANADA(308, "GRD", "GRANADA"),
        GUADALUPE (312, "GLP", "GUADALUPE" ),
        GUAM(316, "GUM", "GUAM"),
        GUATEMALA (320, "GTM", "GUATEMALA" ),
        GUINE(324, "GIN", "GUINÉ"),
        GUIANA (328, "GUY", "GUIANA" ),
        HAITI(332, "HTI", "HAITI"),
        VATICANO(336, "VAT", "VATICANO"),
        APATRIDA(339, "AAA", "APÁTRIDA"),
        HONDURAS(340, "HND", "HONDURAS"),
        CHINA_REGIAO_ADMINISTRATIVA_ESPECIAL_DE_HONG_KONG (344, "HKG", "CHINA, REGIÃO ADMINISTRATIVA ESPECIAL DE HONG KONG"),
        HUNGRIA(348, "HUN", "HUNGRIA"),
        ISLANDIA(352, "ISL", "ISLÂNDIA"),
        INDIA(356, "IND", "ÍNDIA"),
        INDONESIA (360, "IDN", "INDONÉSIA" ),
        IRA_REPUBLICA_ISLAMICA_DO(364, "IRN", "IRÃ (REPÚBLICA ISLÂMICA DO)"),
        IRAQUE (368, "IRQ", "IRAQUE" ),
        IRLANDA(372, "IRL", "IRLANDA"),
        ISRAEL (376, "ISR", "ISRAEL" ),
        ITALIA (380, "ITA", "ITÁLIA" ),
        COSTA_DO_MARFIM(384, "CIV", "COSTA DO MARFIM"),
        JAMAICA(388, "JAM", "JAMAICA"),
        JAPAO(392, "JPN", "JAPÃO"),
        CAZAQUISTAO (398, "KAZ", "CAZAQUISTÃO" ),
        JORDANIA(400, "JOR", "JORDÂNIA"),
        QUENIA (404, "KEN", "QUÊNIA" ),
        COREIA_DO_NORTE(408, "PRK", "COREIA DO NORTE"),
        COREIA_DO_SUL(410, "KOR", "COREIA DO SUL"),
        KUWAIT (414, "KWT", "KUWAIT" ),
        QUIRGUISTAO (417, "KGZ", "QUIRGUISTÃO" ),
        LAOS_REPUBLICA_POPULAR_DEMOCRATICA (418, "LAO", "LAOS, REPÚBLICA POPULAR DEMOCRÁTICA"),
        LIBANO (422, "LBN", "LÍBANO" ),
        LESOTO (426, "LSO", "LESOTO" ),
        LETONIA(428, "LVA", "LETÔNIA"),
        LIBERIA(430, "LBR", "LIBÉRIA"),
        LIBIA(434, "LBY", "LÍBIA"),
        LIECHTENSTEIN(438, "LIE", "LIECHTENSTEIN"),
        LITUANIA(440, "LTU", "LITUÂNIA"),
        LUXEMBURGO(442, "LUX", "LUXEMBURGO"),
        CHINA_REGIAO_ADMINISTRATIVA_ESPECIAL_DE_MACAU(446, "MAC", "CHINA, REGIÃO ADMINISTRATIVA ESPECIAL DE MACAU" ),
        MADAGASCAR(450, "MDG", "MADAGÁSCAR"),
        MALAWI (454, "MWI", "MALAWI" ),
        MALASIA(458, "MYS", "MALÁSIA"),
        MALDIVAS(462, "MDV", "MALDIVAS"),
        MALI(466, "MLI", "MALI"),
        MALTA(470, "MLT", "MALTA"),
        MARTINICA (474, "MTQ", "MARTINICA" ),
        MAURITANIA(478, "MRT", "MAURITÂNIA"),
        MAURICIO(480, "MUS", "MAURÍCIO"),
        MEXICO (484, "MEX", "MÉXICO" ),
        MONACO (492, "MCO", "MÔNACO" ),
        MONGOLIA(496, "MNG", "MONGÓLIA"),
        MOLDAVIA(498, "MDA", "MOLDÁVIA"),
        MONTENEGRO(499, "MNE", "MONTENEGRO"),
        MONTSERRAT(500, "MSR", "MONTSERRAT"),
        MARROCOS(504, "MAR", "MARROCOS"),
        MOCAMBIQUE(508, "MOZ", "MOÇAMBIQUE"),
        OMAN(512, "OMN", "OMAN"),
        NAMIBIA(516, "NAM", "NAMÍBIA"),
        NAURU(520, "NRU", "NAURU"),
        NEPAL(524, "NPL", "NEPAL"),
        HOLANDA(528, "NLD", "HOLANDA"),
        CURACAO(531, "CUW", "CURAÇAO"),
        ARUBA(533, "ABW", "ARUBA"),
        SINT_MAARTEN_PARTE_HOLANDESA(534, "SXM", "SINT MAARTEN (PARTE HOLANDESA)"),
        BONAIRE_SAINT_EUSTATIUS_E_SABA(535, "BES", "BONAIRE, SAINT EUSTATIUS E SABA" ),
        NOVA_CALEDONIA (540, "NCL", "NOVA CALEDÔNIA" ),
        VANUATU(548, "VUT", "VANUATU"),
        NOVA_ZELANDIA(554, "NZL", "NOVA ZELÂNDIA"),
        NICARAGUA (558, "NIC", "NICARÁGUA" ),
        NIGER(562, "NER", "NÍGER"),
        NIGERIA(566, "NGA", "NIGÉRIA"),
        NIUE(570, "NIU", "NIUE"),
        ILHA_NORFOLK(574, "NFK", "ILHA NORFOLK"),
        NORUEGA(578, "NOR", "NORUEGA"),
        ILHAS_MARIANA(580, "MNP", "ILHAS MARIANA"),
        MICRONESIA(583, "FSM", "MICRONESIA"),
        ILHAS_MARSHALL (584, "MHL", "ILHAS MARSHALL" ),
        PALAU(585, "PLW", "PALAU"),
        PAQUISTAO (586, "PAK", "PAQUISTÃO" ),
        PANAMA (591, "PAN", "PANAMÁ" ),
        PAPUA_NOVA_GUINE (598, "PNG", "PAPUA NOVA GUINÉ" ),
        PARAGUAI(600, "PRY", "PARAGUAI"),
        PERU(604, "PER", "PERU"),
        FILIPINAS (608, "PHL", "FILIPINAS" ),
        PITCAIRIN (612, "PCN", "PITCAIRIN" ),
        POLONIA(616, "POL", "POLÔNIA"),
        PORTUGAL(620, "PRT", "PORTUGAL"),
        GUINE_BISSAU(624, "GNB", "GUINÉ BISSAU"),
        TIMOR_LESTE (626, "TLS", "TIMOR LESTE" ),
        PORTO_RICO(630, "PRI", "PORTO RICO"),
        CATAR(634, "QAT", "CATAR"),
        REUNIAO(638, "REU", "REUNIÃO"),
        ROMENIA(642, "ROU", "ROMÊNIA"),
        RUSSIA (643, "RUS", "RÚSSIA" ),
        RUANDA (646, "RWA", "RUANDA" ),
        SAO_BARTOLOMEU (652, "BLM", "SÃO BARTOLOMEU" ),
        SANTA_HELENA(654, "SHN", "SANTA HELENA"),
        SAO_CRISTOVAO_E_NEVIS (659, "KNA", "SÃO CRISTOVÃO E NEVIS" ),
        ANGUILLA(660, "AIA", "ANGUILLA"),
        SANTA_LUCIA (662, "LCA", "SANTA LÚCIA" ),
        SAINT_MARTIN_PARTE_FRANCESA(663, "MAF", "SAINT-MARTIN (PARTE FRANCESA)" ),
        SAINT_PIERRE_E_MIQUELON(666, "SPM", "SAINT PIERRE E MIQUELON"),
        SAO_VICENTE_E_GRANADINAS (670, "VCT", "SÃO VICENTE E GRANADINAS" ),
        SAN_MARINO(674, "SMR", "SAN MARINO"),
        SAO_TOME_E_PRINCIPE (678, "STP", "SÃO TOMÉ E PRÍNCIPE" ),
        SARK(680, "", " SARK"),
        ARABIA_SAUDITA (682, "SAU", "ARÁBIA SAUDITA" ),
        SENEGAL(686, "SEN", "SENEGAL"),
        SERVIA (688, "SRB", "SÉRVIA" ),
        SEYCHELLES(690, "SYC", "SEYCHELLES"),
        SERRA_LEOA(694, "SLE", "SERRA LEOA"),
        CINGAPURA (702, "SGP", "CINGAPURA" ),
        ESLOVAQUIA(703, "SVK", "ESLOVÁQUIA"),
        VIETNA (704, "VNM", "VIETNÃ" ),
        ESLOVENIA (705, "SVN", "ESLOVÊNIA" ),
        SOMALIA(706, "SOM", "SOMÁLIA"),
        AFRICA_DO_SUL(710, "ZAF", "ÁFRICA DO SUL"),
        ZIMBABUE(716, "ZWE", "ZIMBÁBUE"),
        ESPANHA(724, "ESP", "ESPANHA"),
        SUDAO_DO_SUL(728, "SSD", "SUDÃO DO SUL"),
        SUDAO(729, "SDN", "SUDÃO"),
        SAARA_OCIDENTAL(732, "ESH", "SAARA OCIDENTAL"),
        SURINAME(740, "SUR", "SURINAME"),
        SVALBARD_E_JAN_MAYER(744, "SJM", "SVALBARD E JAN MAYER"),
        SUAZILANDIA (748, "SWZ", "SUAZILÂNDIA" ),
        SUECIA (752, "SWE", "SUÉCIA" ),
        SUICA(756, "CHE", "SUÍÇA"),
        SIRIA(760, "SYR", "SÍRIA"),
        TAJIQUISTAO (762, "TJK", "TAJIQUISTÃO" ),
        TAILANDIA (764, "THA", "TAILÂNDIA" ),
        TOGO(768, "TGO", "TOGO"),
        TOKELAU(772, "TKL", "TOKELAU"),
        TONGA(776, "TON", "TONGA"),
        TRINDADE_E_TOBAGO(780, "TTO", "TRINDADE E TOBAGO"),
        EMIRADOS_ARABES_UNIDOS(784, "ARE", "EMIRADOS ÁRABES UNIDOS"),
        TUNISIA(788, "TUN", "TUNÍSIA"),
        TURQUIA(792, "TUR", "TURQUIA"),
        TURQUEMENISTAO (795, "TKM", "TURQUEMENISTÃO" ),
        ILHAS_TURKS_E_CAICOS(796, "TCA", "ILHAS TURKS E CAICOS"),
        TUVALU (798, "TUV", "TUVALU" ),
        UGANDA (800, "UGA", "UGANDA" ),
        UCRANIA(804, "UKR", "UCRÂNIA"),
        REPUBLICA_DA_MACEDONIA(807, "MKD", "REPÚBLICA DA MACEDÔNIA"),
        EGITO(818, "EGY", "EGITO"),
        REINO_UNIDO_DA_GRA_BRETANHA_E_IRLANDA_DO_NORTE (826, "GBR", "REINO UNIDO DA GRÃ BRETANHA E IRLANDA DO NORTE" ),
        ILHAS_DO_CANAL (830, "", "ILHAS DO CANAL" ),
        GUERNSEY(831, "GGY", "GUERNSEY"),
        JERSEY (832, "JEY", "JERSEY" ),
        ILHAS_DE_MAN(833, "IMN", "ILHAS DE MAN"),
        TANZANIA(834, "TZA", "TANZÂNIA"),
        ESTADOS_UNIDOS_DA_AMERICA(840, "USA", "ESTADOS UNIDOS DA AMÉRICA"),
        ILHAS_VIRGENS_AMERICANAS (850, "VIR", "ILHAS VIRGENS AMERICANAS" ),
        BURQUINA_FASO(854, "BFA", "BURQUINA FASO"),
        URUGUAI(858, "URY", "URUGUAI"),
        UZBEQUISTAO (860, "UZB", "UZBEQUISTÃO" ),
        VENEZUELA (862, "VEN", "VENEZUELA" ),
        ILHAS_WALLIS_E_FUTUNA (876, "WLF", "ILHAS WALLIS E FUTUNA" ),
        SAMOA(882, "WSM", "SAMOA"),
        IEMEN(887, "YEM", "IÉMEN"),
        ZAMBIA (894, "ZMB", "ZÂMBIA" ),
        OUTRA_NACIONALIDADE (999, "OOO", "OUTRA NACIONALIDADE" );

        private final int valor;
        private final String abreviatura;
        private final String descricao;

        Paises(int valor, String abreviatura, String descricao) {
                this.valor = valor;
                this.abreviatura = abreviatura;
                this.descricao = descricao;
        }

        public static Paises getValorPorDescricao(int valor) {
                for (Paises status : values())
                        if (status.getValor() == valor)
                                return status;

                return null;
        }

        private Object getDescricao() {
                return descricao;
        }

        public int getValor() {
                return this.valor;
        }

}
