CREATE SEQUENCE UNIDADE_ENSINO_ID_SEQ;

CREATE TABLE IF  NOT EXISTS UNIDADE_ENSINO (id INTEGER UNIQUE DEFAULT nextval('UNIDADE_ENSINO_ID_SEQ'),
                                            codigo_inep INTEGER PRIMARY KEY NOT NULL,
                                            nome VARCHAR (100),
                                            tipo_registro INTEGER,
                                            situacao_funcionamento INTEGER,
                                            data_incio_ano_letivo DATE,
                                            data_termino_ano_letivo DATE,
                                            telefone INTEGER,
                                            outro_telefone_contato INTEGER,
                                            endereco_eletronico_email_escola VARCHAR (50),
                                            codigo_orgao_regional_ensino VARCHAR (5),
                                            localizacao_zona_escola INTEGER,
                                            localizacao_diferenciada_escola INTEGER,
                                            dependencia_administrativa INTEGER,
                                            secretaria_educacao BOOLEAN,
                                            ssecretaria_seguranca_publica BOOLEAN,
                                            secretaria_saude BOOLEAN,
                                            outro_orgao_administracao_publica BOOLEAN,
                                            secretaria_estadual BOOLEAN,
                                            secretaria_municipal BOOLEAN,
                                            nao_possui_parceria_convenio BOOLEAN,
                                            esfera_administrativa_id INTEGER,
                                            endereco_unidade_id INTEGER,
                                            mantenedora_escola_privada_id INTEGER,
                                            formas_contratacao_id INTEGER,
                                            numero_matriculas_atendidas_parceria_convenio_id INTEGER,
                                            local_funcionamento_escola_id INTEGER,
                                            escolas_com_qual_compartilha_id INTEGER,
                                            abastecimento_agua_id INTEGER,
                                            fonte_energia_eletrica_id INTEGER,
                                            esgotamento_sanitario_id INTEGER,
                                            destinacao_lixo_id INTEGER,
                                            tratamento_lixo_id INTEGER,
                                            dependencias_fisicas_id INTEGER,
                                            recurso_pessoas_deficientes_id INTEGER,
                                            equipamentos_existentes_unidade_id INTEGER,
                                            quantidade_equipamentos_processo_aprendizagem_id INTEGER,
                                            quantidade_computadores_em_uso_alunos_id INTEGER,
                                            acesso_internet_id INTEGER,
                                            equipamentos_usados_alunos_acesso_internet_id INTEGER,
                                            rede_local_interligacao_computadores_id INTEGER,
                                            instrumentos_materiais_socio_culturais_id INTEGER,
                                            idioma_ensino_id INTEGER,
                                            reserva_vagas_sistema_cotas_id INTEGER,
                                            orgaos_colegiados_funcionamento_escola_id INTEGER,
                                            total_profissionais_ativos_escola_id INTEGER

);

ALTER SEQUENCE UNIDADE_ENSINO_ID_SEQ
    OWNED BY UNIDADE_ENSINO.ID;