CREATE SEQUENCE LINGUA_INDIGENA_ID_SEQ;

CREATE TABLE IF NOT EXISTS LINGUA_INDIGENA   (id INTEGER PRIMARY KEY DEFAULT nextval('LINGUA_INDIGENA_ID_SEQ')

);
ALTER SEQUENCE LINGUA_INDIGENA_ID_SEQ
    OWNED BY LINGUA_INDIGENA.id;
