CREATE SEQUENCE NUMERO_MATRICULAS_ATENDIDAS_PARCERIA_CONVENIO_ID_SEQ;

CREATE TABLE IF NOT EXISTS NUMERO_MATRICULAS_ATENDIDAS_PARCERIA_CONVENIO (id INTEGER PRIMARY KEY DEFAULT nextval('NUMERO_MATRICULAS_ATENDIDAS_PARCERIA_CONVENIO_ID_SEQ'),
                                                                          atividade_complementar INTEGER,
                                                                          atendimento_educacional_especializado INTEGER,
                                                                          ensino_regular_creche_parc INTEGER,
                                                                          ensino_regular_creche_integ INTEGER,
                                                                          ensino_regular_pre_escola_parc INTEGER,
                                                                          ensino_regular_pre_escola_integ INTEGER,
                                                                          ensino_regular_ensino_fundamental_anos_iniciais_parc INTEGER,
                                                                          ensino_regular_ensino_fundamental_anos_iniciais_integ INTEGER,
                                                                          ensino_regular_ensino_fundamental_anos_finais_parc INTEGER,
                                                                          ensino_regular_ensino_fundamental_anos_finais_integ INTEGER,
                                                                          ensino_regular_ensino_medio_parc INTEGER,
                                                                          ensino_regular_ensino_medio_integ INTEGER,
                                                                          edu_especial_classe_especial_parc INTEGER,
                                                                          edu_especial_classe_especial_integ INTEGER,
                                                                          edu_jov_adult_ensino_fundamental_medio_parc INTEGER,
                                                                          edu_jov_adult_ensino_fundamental_medio_integ INTEGER,
                                                                          edu_prof_qual_integ_jov_adult_ensino_fundamental_parc INTEGER,
                                                                          edu_prof_qual_integ_jov_adult_ens_fund_integ INTEGER,
                                                                          edu_prof_qual_tec_integ_jov_adult_niv_medio_parc INTEGER,
                                                                          edu_prof_qual_tec_integ_jov_adult_niv_medio_integ INTEGER,
                                                                          edu_prof_qual_prof_tec_concomit_edu_jov_adult_niv_med_parc INTEGER,
                                                                          edu_prof_qual_prof_tec_concomit_edu_jov_adult_niv_med_integ INTEGER,
                                                                          edu_qual_prof_tec_concom_inter_compl_edu_jov_adu_niv_medio_parc INTEGER,
                                                                          edu_qual_prof_tec_concom_inter_compl_edu_jov_adu_niv_med_integ INTEGER,
                                                                          edu_prof_qual_prof_tec_integ_ens_med_parc INTEGER,
                                                                          edu_prof_qual_prof_tec_integ_ens_med_integ INTEGER,
                                                                          edu_pro_qual_prof_tec_concomit_ens_med_parc INTEGER,
                                                                          edu_pro_qual_prof_tec_concomit_ens_med_integ INTEGER,
                                                                          edu_pro_qual_prof_tec_concomit_inter_compl_ens_med_parc INTEGER,
                                                                          edu_pro_qual_prof_tec_concomit_inter_compl_ens_med_integ INTEGER,
                                                                          edu_prof_edu_prof_tec_niv_med_integ_edu_jov_adult_niv_med_parc INTEGER,
                                                                          edu_prof_edu_prof_tec_niv_med_integ_edu_jov_adult_niv_med_integ INTEGER,
                                                                          edu_prof_tec_niv_med_concomit_edu_jov_adult_niv_med_parc INTEGER,
                                                                          edu_prof_tec_niv_med_concomit_edu_jov_adult_niv_med_integ INTEGER,
                                                                          edu_prof_tec_niv_med_concomit_int_edu_jov_adult_niv_med_integ INTEGER,
                                                                          edu_prof_tec_niv_med_concomit_int_edu_jov_adult_niv_med_parc INTEGER,
                                                                          edu_prof_tec_niv_med_integ_ens_med_parc INTEGER,
                                                                          edu_prof_tec_niv_med_integ_ens_med_integ INTEGER,
                                                                          edu_prof_tec_niv_med_concomit_ens_med_parc INTEGER,
                                                                          edu_prof_tec_niv_med_subsequente_ens_med INTEGER,
                                                                          edu_prof_tec_niv_med_concomit_ens_med_integ INTEGER,
                                                                          edu_prof_tec_niv_med_concomit_inter_compl_ens_medio_parc INTEGER,
                                                                          edu_prof_tec_niv_medio_concomit_inter_comple_ens_medio_integ INTEGER,
                                                                          cnpj_mantenedora_princ_escola_privada VARCHAR (14),
                                                                          reg_autor_conselho_orgao_mun_est_fed_edu INTEGER
);
ALTER SEQUENCE NUMERO_MATRICULAS_ATENDIDAS_PARCERIA_CONVENIO_ID_SEQ
    OWNED BY NUMERO_MATRICULAS_ATENDIDAS_PARCERIA_CONVENIO.id;
