package br.com.coreeduc.aplication.records;

import java.util.Date;

public record UnitEducacensoRecord(Long codeInep,
                                   String name,
                                   Integer operatingStatus,
                                   Date dateStartYearSchool,
                                   Date dateEndYearSchool,
                                   Integer telephone,
                                   Integer otherPhoneContact,
                                   String addressElectronicEmailSchool,
                                   String regionalEducationBodyCode,
                                   Integer locationSchoolZone,
                                   Integer locationDifferentiatedSchool,
                                   Integer dependencyAdministrative,
                                   Integer secretariatEducation,
                                   Integer publicSecuritySecretariat,
                                   Integer secretaryHealth,
                                   Integer otherPublicAdministrationBody,
                                   Integer stateSecretariat,
                                   Integer municipalSecretariat,
                                   Integer NoPartnershipAgreement,
                                   AdministrativeSphereEducacensoRecord administrativeSphereEducacensoRecord,
                                   AdressUnitEducacensoRecord adressUnitEducacensoRecord,
                                   PrivateSchoolSupporterEducacensoRecord privateSchoolSupporterEducacensoRecord,
                                   FormsOfHiringEducacensoRecord formsOfHiringEducacensoRecord,
                                   NumberRegistrationsServedPartnershipAgreementEducacensoRecord numberRegistrationsServedPartnershipAgreementEducacensoRecord,
                                   SchoolLocationEducacensoRecord schoolLocationEducacensoRecord,
                                   SchoolParticipationEducacensoRecord schoolParticipationEducacensoRecord,
                                   WaterSupplyEducacensoRecord waterSupplyEducacensoRecord,
                                   ElectricEnergySourceEducacensoRecord electricEnergySourceEducacensoRecord,
                                   SanitarySewageEducacensoRecord sanitarySewageEducacensoRecord,
                                   WasteDisposalEducacensoRecord wasteDisposalEducacensoRecord,
                                   WasteTreatmentEducacensoRecord wasteTreatmentEducacensoRecord,
                                   PhysicalDependenciesEducacensoRecord physicalDependenciesEducacensoRecord,
                                   DisabledPeopleResourceEducacensoRecord disabledPeopleResourceEducacensoRecord,
                                   ExistingUnitEquipmentEducacensoRecord existingUnitEquipmentEducacensoRecord,
                                   QuantityEquipmentLearningProcessEducacensoRecord quantityEquipmentLearningProcessEducacensoRecord,
                                   NumberComputersInUseByStudentsEducacensoRecord numberComputersInUseByStudentsEducacensoRecord,
                                   InternetAccessEducacensoRecord internetAccessEducacensoRecord,
                                   UsedEquipmentStudentsInternetAccessEducacensoRecord usedEquipmentStudentsInternetAccessEducacensoRecord,
                                   LocalNetworkInterconnectionComputersEducacensoRecord localNetworkInterconnectionComputersEducacensoRecord,
                                   TotalProfessionalsActivesSchoolEducacensoRecord totalProfessionalsActivesSchoolEducacensoRecord,
                                   InstrumentsMaterialsSocioCulturalEducacensoRecord instrumentsMaterialsSocioCulturalEducacensoRecord,
                                   LanguageTeachingEducacensoRecord languageTeachingEducacensoRecord,
                                   ReservationVacanciesSystemQuotasEducacensoRecord reservationVacanciesSystemQuotasEducacensoRecord,
                                   OrganizationsCollegiateOperationSchoolEducacensoRecord organizationsCollegiateOperationSchoolEducacensoRecord) {
}
