CREATE SEQUENCE ESGOTAMENTO_SANITARIO_ID_SEQ;

CREATE TABLE IF NOT EXISTS ESGOTAMENTO_SANITARIO
(
    id                            INTEGER PRIMARY KEY DEFAULT nextval('ESGOTAMENTO_SANITARIO_ID_SEQ'),
    rede_publica                  BOOLEAN DEFAULT FALSE,
    fossa_septica                 BOOLEAN DEFAULT FALSE,
    fossa_rudimentar_comum        BOOLEAN DEFAULT FALSE,
    nao_ha_esgostamento_sanitario BOOLEAN DEFAULT FALSE
);
ALTER SEQUENCE ESGOTAMENTO_SANITARIO_ID_SEQ
    OWNED BY ESGOTAMENTO_SANITARIO.id;
