CREATE SEQUENCE EQUIPAMENTOS_USADOS_ALUNOS_ACESSO_INTERNET_ID_SEQ;

CREATE TABLE IF NOT EXISTS EQUIPAMENTOS_USADOS_ALUNOS_ACESSO_INTERNET
(
    id                                           INTEGER PRIMARY KEY DEFAULT nextval('EQUIPAMENTOS_USADOS_ALUNOS_ACESSO_INTERNET_ID_SEQ'),
    computadores_tablets_biblioteca_unidade      BOOLEAN DEFAULT FALSE,
    dispositivos_pessoais_computadores_portateis BOOLEAN DEFAULT FALSE,
    internet_banda_larga                         BOOLEAN DEFAULT FALSE
);
ALTER SEQUENCE EQUIPAMENTOS_USADOS_ALUNOS_ACESSO_INTERNET_ID_SEQ
    OWNED BY EQUIPAMENTOS_USADOS_ALUNOS_ACESSO_INTERNET.id;
