INSERT INTO disciplinas (codigo_mec, nome, fk_codigo_area_conhecimento) VALUES (1, 'Química', 3);
INSERT INTO disciplinas (codigo_mec, nome, fk_codigo_area_conhecimento) VALUES (2, 'Física', 3);
INSERT INTO disciplinas (codigo_mec, nome, fk_codigo_area_conhecimento) VALUES (3, 'Matemática', 2);
INSERT INTO disciplinas (codigo_mec, nome, fk_codigo_area_conhecimento) VALUES (4, 'Biologia', 3);
INSERT INTO disciplinas (codigo_mec, nome, fk_codigo_area_conhecimento) VALUES (5, 'Ciências', 3);
INSERT INTO disciplinas (codigo_mec, nome, fk_codigo_area_conhecimento) VALUES (6, 'Língua /Literatura Portuguesa ', 1);
INSERT INTO disciplinas (codigo_mec, nome, fk_codigo_area_conhecimento) VALUES (7, 'Língua /Literatura estrangeira - Inglês ', 1);
INSERT INTO disciplinas (codigo_mec, nome, fk_codigo_area_conhecimento) VALUES (8, 'Língua /Literatura estrangeira - Espanhol', 1);
INSERT INTO disciplinas (codigo_mec, nome, fk_codigo_area_conhecimento) VALUES (9, 'Língua /Literatura estrangeira - outra', 1);
INSERT INTO disciplinas (codigo_mec, nome, fk_codigo_area_conhecimento) VALUES (10, 'Arte', 1);
INSERT INTO disciplinas (codigo_mec, nome, fk_codigo_area_conhecimento) VALUES (11, 'Educação Física', 1);
INSERT INTO disciplinas (codigo_mec, nome, fk_codigo_area_conhecimento) VALUES (12, 'História', 4);
INSERT INTO disciplinas (codigo_mec, nome, fk_codigo_area_conhecimento) VALUES (13, 'Geografia', 4);
INSERT INTO disciplinas (codigo_mec, nome, fk_codigo_area_conhecimento) VALUES (14, 'Filosofia', 4);
INSERT INTO disciplinas (codigo_mec, nome, fk_codigo_area_conhecimento) VALUES (16, 'Informática', 5);
INSERT INTO disciplinas (codigo_mec, nome, fk_codigo_area_conhecimento) VALUES (17, 'Áreas do conhecimento profissionalizantes', 5);
INSERT INTO disciplinas (codigo_mec, nome, fk_codigo_area_conhecimento) VALUES (23, 'Líbras', 1);
INSERT INTO disciplinas (codigo_mec, nome, fk_codigo_area_conhecimento) VALUES (25, 'Áreas do conhecimento pedagógica', 5);
INSERT INTO disciplinas (codigo_mec, nome, fk_codigo_area_conhecimento) VALUES (26, 'Ensino Religioso', 5);
INSERT INTO disciplinas (codigo_mec, nome, fk_codigo_area_conhecimento) VALUES (27, 'Língua indígena', 1);
INSERT INTO disciplinas (codigo_mec, nome, fk_codigo_area_conhecimento) VALUES (28, 'Estudos sociais', 4);
INSERT INTO disciplinas (codigo_mec, nome, fk_codigo_area_conhecimento) VALUES (29, 'Sociologia', 4);
INSERT INTO disciplinas (codigo_mec, nome, fk_codigo_area_conhecimento) VALUES (30, 'Língua/Literatura estrangeira - Francês', 1);
INSERT INTO disciplinas (codigo_mec, nome, fk_codigo_area_conhecimento) VALUES (31, 'Língua Portuguesa como Segunda Língua', 1);
INSERT INTO disciplinas (codigo_mec, nome, fk_codigo_area_conhecimento) VALUES (32, 'Estágio curricular supervisionado', 5);
INSERT INTO disciplinas (codigo_mec, nome, fk_codigo_area_conhecimento) VALUES (99, 'Outras áreas do conhecimento', 5);