CREATE SEQUENCE PROFESSOR_ID_SEQ;

CREATE TABLE IF NOT EXISTS PROFESSOR
(
    id        INTEGER UNIQUE DEFAULT nextval('PROFESSOR_ID_SEQ'),
    pessoa_codigo INTEGER,
    CONSTRAINT fk_pessoa FOREIGN KEY (pessoa_codigo)
        REFERENCES pessoa (codigo)
);

ALTER SEQUENCE PROFESSOR_ID_SEQ
    OWNED BY PROFESSOR.ID;
