CREATE SEQUENCE PROFESSOR_ID_SEQ;

CREATE TABLE IF NOT EXISTS PROFESSOR
(
    id        INTEGER UNIQUE DEFAULT nextval('PROFESSOR_ID_SEQ'),
    pessoa_id INTEGER,
    CONSTRAINT fk_pessoa FOREIGN KEY (pessoa_id)
        REFERENCES pessoa (id)
);

ALTER SEQUENCE PROFESSOR_ID_SEQ
    OWNED BY PROFESSOR.ID;
