CREATE SEQUENCE COMPOSICAO_ENSINO_ID_SEQ;

CREATE TABLE IF NOT EXISTS COMPOSICAO_ENSINO
(
    id                    INTEGER UNIQUE DEFAULT nextval('COMPOSICAO_ENSINO_ID_SEQ'),
    nome                  varchar(70),
    criterio_avaliacao_id INTEGER

);

ALTER SEQUENCE COMPOSICAO_ENSINO_ID_SEQ
    OWNED BY COMPOSICAO_ENSINO.ID;


