CREATE SEQUENCE ALUNO_ID_SEQ;

CREATE TABLE IF NOT EXISTS ALUNO
(
    id        INTEGER PRIMARY KEY DEFAULT nextval('ALUNO_ID_SEQ'),
    pessoa_codigo INTEGER,
    CONSTRAINT fk_pessoa FOREIGN KEY (pessoa_codigo)
        REFERENCES pessoa (codigo)
);

ALTER SEQUENCE ALUNO_ID_SEQ
    OWNED BY ALUNO.ID;
