CREATE SEQUENCE HORARIO_FUNCIONAMENTO_ID_SEQ;

CREATE TABLE IF NOT EXISTS HORARIO_FUNCIONAMENTO
(
    id            INTEGER UNIQUE DEFAULT nextval('HORARIO_FUNCIONAMENTO_ID_SEQ'),
    HORA_INICIAL  VARCHAR,
    MINUTO_INICIAL  VARCHAR,
    HORA_FINAL  VARCHAR,
    MINUTO_FINAL  VARCHAR
);

ALTER SEQUENCE HORARIO_FUNCIONAMENTO_ID_SEQ
    OWNED BY HORARIO_FUNCIONAMENTO.ID;