CREATE SEQUENCE DIAS_SEMANA_TURMA_ID_SEQ;

CREATE TABLE IF NOT EXISTS DIAS_SEMANA_TURMA
(
    ID            INTEGER UNIQUE DEFAULT nextval('DIAS_SEMANA_TURMA_ID_SEQ'),
    DOMINGO  BOOLEAN,
    SEGUNDA  BOOLEAN,
    TERCA  BOOLEAN,
    QUARTA  BOOLEAN,
    QUINTA  BOOLEAN,
    SEXTA  BOOLEAN,
    SABADO  BOOLEAN
);

ALTER SEQUENCE DIAS_SEMANA_TURMA_ID_SEQ
    OWNED BY DIAS_SEMANA_TURMA.ID;