CREATE SEQUENCE FORMA_ORGANIZACAO_ID_SEQ;

CREATE TABLE IF NOT EXISTS FORMA_ORGANIZACAO
(
    ID INTEGER UNIQUE DEFAULT nextval('FORMA_ORGANIZACAO_ID_SEQ'),
    SERIES_ANUAIS  BOOLEAN,
    PERIODOS_SEMESTRAIS  BOOLEAN,
    CICLOS  BOOLEAN,
    GRUPOS_NAO_SERIADOS  BOOLEAN,
    MODULOS  BOOLEAN,
    ALTERNANCIA_PERIODOS  BOOLEAN
);

ALTER SEQUENCE FORMA_ORGANIZACAO_ID_SEQ
    OWNED BY FORMA_ORGANIZACAO.ID;