CREATE SEQUENCE UNIDADE_CURRICULAR_TURMA_ID_SEQ;

CREATE TABLE IF NOT EXISTS UNIDADE_CURRICULAR_TURMA
(
    ID INTEGER UNIQUE DEFAULT nextval('UNIDADE_CURRICULAR_TURMA_ID_SEQ'),
    ELETIVAS  BOOLEAN,
    LIBRAS  BOOLEAN,
    LINGUA_INDIGENA  BOOLEAN,
    LINGUA_LIT_ESPANHOL  BOOLEAN,
    LINGUA_LIT_FRANCES  BOOLEAN,
    LINGUA_LIT_OUTRAS  BOOLEAN,
    PROJETO_VIDA  BOOLEAN,
    TRILHA_APROF_APRENDIZAGEM  BOOLEAN
);

ALTER SEQUENCE UNIDADE_CURRICULAR_TURMA_ID_SEQ
    OWNED BY UNIDADE_CURRICULAR_TURMA.ID;