CREATE SEQUENCE COMPANY_ID_SEQ;

CREATE TABLE IF NOT EXISTS COMPANY
(
    ID INTEGER UNIQUE DEFAULT nextval('COMPANY_ID_SEQ'),
    FANTASY_NAME  VARCHAR(150)
);

ALTER SEQUENCE COMPANY_ID_SEQ
    OWNED BY COMPANY.ID;