CREATE SEQUENCE SESSION_BRANCH_ACTING_ID_SEQ;

CREATE TABLE IF NOT EXISTS SESSION_BRANCH_ACTING
(
    ID INTEGER UNIQUE DEFAULT nextval('SESSION_BRANCH_ACTING_ID_SEQ'),
    CODE  VARCHAR(30),
    DESCRIPTION text
);

ALTER SEQUENCE SESSION_BRANCH_ACTING_ID_SEQ
    OWNED BY SESSION_BRANCH_ACTING.ID;