CREATE SEQUENCE DIVISION_GROUP_BRANCH_ACTING_ID_SEQ;

CREATE TABLE IF NOT EXISTS DIVISION_GROUP_BRANCH_ACTING
(
    ID INTEGER UNIQUE DEFAULT nextval('DIVISION_GROUP_BRANCH_ACTING_ID_SEQ'),
    DESCRIPTION  text,
    CODE  VARCHAR(30),
    session_branch_acting_id INTEGER,
    CONSTRAINT fk_session_branch_acting FOREIGN KEY (session_branch_acting_id)
        REFERENCES session_branch_acting (id)
);

ALTER SEQUENCE DIVISION_GROUP_BRANCH_ACTING_ID_SEQ
    OWNED BY DIVISION_GROUP_BRANCH_ACTING.ID;