CREATE SEQUENCE NEIGHBORDHOOD_ID_SEQ;

CREATE TABLE IF NOT EXISTS NEIGHBORDHOOD
(
    ID INTEGER UNIQUE DEFAULT nextval('NEIGHBORDHOOD_ID_SEQ'),
    DESCRIPTION text,
    CITY_ID INTEGER,
    CONSTRAINT fk_city FOREIGN KEY (city_id)
        REFERENCES city (id)
);

ALTER SEQUENCE NEIGHBORDHOOD_ID_SEQ
    OWNED BY NEIGHBORDHOOD.ID;