CREATE SEQUENCE NEIGHBORDHOOD_ID_SEQ;

CREATE TABLE IF NOT EXISTS NEIGHBORDHOOD
(
    ID INTEGER UNIQUE DEFAULT nextval('NEIGHBORDHOOD_ID_SEQ'),
    DESCRIPTION text,
    CITY_codigo_mec INTEGER,
    CONSTRAINT fk_city FOREIGN KEY (CITY_codigo_mec)
        REFERENCES CITY (codigo_mec)
);

ALTER SEQUENCE NEIGHBORDHOOD_ID_SEQ
    OWNED BY NEIGHBORDHOOD.ID;